name: Presig Tests
on: [push, pull_request]
runs-on: ${{ matrix.os }}

strategy:
    matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]
        python-version: 3.7
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
        run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
        run: |
        python test_presig.py
