name: Presig Tests
on: [push, pull_request]
runs-on: ${{ matrix.os }}

strategy:
    matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest] 
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
